### PR TITLE
Support bearer token with JUnit annotations - Fixes gh-925

### PR DESCRIPTION
**Pull request by tinexw**
I decided to do the first option since it was easier to implement. Should I add checks somewhere that the correct combination of values is set?

### CODE REVIEW

**Comment by uglyog** [comment]
I think the scheme can be defaulted if the token property is set. That way people will only need to set the token value. I.e.,

```java

**Comment by tinexw** [comment]
Yes, makes sense. Will add this.

**Comment by tinexw** [comment]
I changed the implementation so that it is now possible to say

```
authentication = @PactBrokerAuth(token = "test")
```

I marked the schema as deprecated. It is now automatically set to
- `Basic` if the username is set
- `Bearer` if the token is set

I  hope marking it as deprecated is ok. It did not see it being used anywhere. Please let me know if it is actually of use somewhere and we should keep it.

**Comment by uglyog** [comment]
Deprecated makes sense. It's really there in case other authentication schemes are required, but the implementation would not be supported so it is redundant.

**Pull request merged**
