### PR TITLE
Add teardown support to JUnit provider

### PR DESCRIPTION
**Pull request by tinexw**
Hi, 

this is a first attempt at adding teardown support to the Junit provider. Are you ok with this approach in general or would you prefer a different one?
Where should I add the tests? There are groovy, java and kotlin folders and I don't know where to put them.

### CODE REVIEW

**Comment by uglyog** [comment]
This is a good start. You can write the tests in the language you are most comfortable with.

**Comment by tinexw** [comment]
I added a test. Let me know if anything else is missing.

**Comment by tinexw** [comment]
@uglyog Did you have a chance to look at my changes?

**Comment by uglyog** [comment]
The only thing that is missing is to update RunStateChanges so it invokes the teardown method afterwards.

**Comment by tinexw** [comment]
It's invoked in the InteractionRunner. Does it really need to be invoked somewhere else?

**Comment by uglyog** [comment]
It is invoked, but only runs before the interactions. It needs to also run the teardowns after. But I will sort that out for you.

**Comment by uglyog** [comment]
It was actually running the teardown first, then the setup, then the interaction. I have refactored it a bit, and implemented the execution order correctly. The missing bit was https://github.com/DiUS/pact-jvm/blob/v3.5.x/pact-jvm-provider-junit/src/main/java/au/com/dius/pact/provider/junit/RunStateChanges.java#L27

**Comment by uglyog** [comment]
3.5.22 has been released with this feature

**Comment by tinexw** [comment]
Thanks!

**Pull request merged**
