### PR TITLE
fix: 916 use groovy 3

### PR DESCRIPTION
**Pull request by cogman**
This still fails some ABC code narc tests.  Does anyone have a suggestion on how to resolve this?

Fixes issue- #916

### CODE REVIEW

**Comment by uglyog** [comment]
ABC normally indicates methods that are too complex, but maybe that is CodeNarc not dealing with Groovy 3. I can have a look into fixing that.

**Comment by cogman** [comment]
@uglyog  Thanks for looking into this.  It may just be that the switch to http-builder-ng pushed it over the edge.  It changed the parameters from maps to more of a DSL which means more assignments.

I didn't want to do a whole lot of restructuring of tests so I backed off with just the narcs I could simply solve.  As is it should be pretty close to the same flow it was before my tinkering.

**Comment by uglyog** [comment]
I've fixed the ABC metric violation, as well as some other tests that still were using the old HTTPBuilder.

The next big problem is the Gradle plugin. This has to be compiled against the version of Groovy included with Gradle, which is currently 2.5.4. This causes an issue with both Groovy and Spock in that module.

**Comment by uglyog** [comment]
Green build!

**Comment by cogman** [comment]
Thanks for taking this past the finish line!

**Comment by uglyog** [comment]
4.0.6 has been released

**Pull request merged**
