### PR TITLE
fix: backward compatible support for Z UTC designator in timestamps

### PR DESCRIPTION
**Pull request by anto-ac**
@uglyog what do you think about this? Perhaps a bit hacky, but at the same time there might be other organisations in a similar situation to ours.

### CODE REVIEW

**Comment by uglyog** [comment]
Although it feels like a bad thing to do, it looks like it might be ok. It looks like ISO 8601 Time zone designation is a superset of the RFC 822 one. But maybe we should output a warning that the substitution has been made?

**Comment by anto-ac** [comment]
Good point on the warning. 

I’ve just realised that my change wouldn’t take into account formats with quotes though, and I think the parsing would fail in that case.

**Comment by uglyog** [comment]
Ah, yeah, that's a problem.

I'm thinking we can add a JVM system property that turns on the behaviour. That way it is opt in.

**Comment by anto-ac** [comment]
Or... I was thinking... a regex that substitutes only Z that are not enclosed in quotes

**Comment by anto-ac** [comment]
@aplsup @e-ivaldi @uglyog If I could get your reviews/approvals, that would be great.

**Pull request merged**
