### PR TITLE
Implement fixes merged to master instead of 4.1.x branch

### PR DESCRIPTION
**Pull request by jgelon**
Not sure if this is the way to go. But I saw my changes were merged to master, however during the release of 4.1.3 the changes were not there.

Please close PR if this is being done in another way by DiUS

### CODE REVIEW

**Comment by anto-ac** [comment]
@jgelon 4.1.3 was intentionally released not from `master` because at the time of release there were issues in `master`.
I imagine we'll be able to release soon again directly from `master`.

**Comment by anto-ac** [comment]
@jgelon I'm probably going to release from `master` at some point today

**Comment by jgelon** [comment]
> @jgelon I'm probably going to release from `master` at some point today
Awesome :D

Should this PR be closed then?

**Comment by anto-ac** [comment]
Probably better to close this PR, yes - I am in the process of upgrading, but oss.sonatype.org is under maintainance, so I'm blocked until they resume their services.

**Comment by jgelon** [comment]
@anto-ac seems like its back up

**Comment by anto-ac** [comment]
Still in maintainance https://status.maven.org/

**Comment by jgelon** [comment]
@anto-ac will the master be merged into 4.1.x branch soon?

**Comment by anto-ac** [comment]
@jgelon Your changes should be are already out with 4.1.4.

As far as I understand, the preference is to release from master, which is what I did last Friday, unless there is a specific reason not to do it. Any reason why you’d want master merged into 4.1.x?

**Comment by uglyog** [comment]
At the moment, master and 4.1.x will be the same. Once we move to 4.2.x, they will then diverge.

**Pull request closed without merging**
