### PR TITLE
update `PactBroker` to allow setting properties via system properties by default

### PR DESCRIPTION
**Pull request by Fitzoh**
For some reason master wasn't building on my machine.
I have more documenting to do but wanted to see what travis had to say.

### CODE REVIEW

**Comment by cah-andrewfitzgerald** [comment]
Updated with documentation

**Comment by Fitzoh** [comment]
Updated with documentation

**Comment by Fitzoh** [comment]
This works, but feels a little bit janky. Any thoughts @uglyog ?

**Comment by uglyog** [comment]
Looks good to me. I'll change the default authentication scheme to `basic`, as `none` does not make sense, now that I think of it.

**Pull request merged**
