### PR TITLE
fix: Don't send successfull verification result to the Broker if not all interactions are verified

### PR DESCRIPTION
**Pull request by aplsup**
…all interactions are verified

### CODE REVIEW

**Comment by uglyog** [comment]
Thanks for the PR! Does this fix #889, or is there still more needed?

I will backport it into the 3.6.x branch.

**Comment by aplsup** [comment]
Actually I was thinking if we need some sort of global aggregation of all the test class with a PactRunner. While this PR prevents false positives, in the case where the verification tests for a PACT are split among different classes (filtered) the verification won’t be considered successful even if it semantically is.

**Comment by anto-ac** [comment]
@uglyog What do you think about @aplsup consideration above?

Also, when you reckon we could have a 3.6.8 release?

**Comment by uglyog** [comment]
I have cherry-picked the changes onto the v3.6.x branch.

A global aggregation will work as long as the tests run in the same JVM. If parallel test execution is enabled, then it won't work.

**Comment by uglyog** [comment]
I'll organise a release this weekend

**Pull request merged**
